language: cpp

branches:
  only:
    - master

env:
  global:
    - CXXFLAGS="-W -Wall"
  matrix:
    # gcc builds
    - BUILD_CC="gcc" BUILD_CXX="g++"
    # clang builds
    - BUILD_CC="clang" BUILD_CXX="clang++"

install:
  - sudo apt-get -qq update
  - sudo apt-get install libsdl1.2-dev libwxgtk3.0-dev

before_script:
  - mkdir build && cd build && ../configure CC=$BUILD_CC CXX=$BUILD_CXX

script:
  - make
  - make check
